// Lightweight, local ingredient-to-common-use mapping used only to enrich
// embedding text. It is NOT clinical advice and does not create new medicine
// records; it simply tells the embedding model what a product is typically
// used for, so symptom-style queries can find relevant medicines from the
// existing database.

const INGREDIENT_USES = {
  Paracetamol: 'pain, fever, headache, bodyache',
  Ibuprofen: 'pain, fever, headache, inflammation, arthritis',
  Aspirin: 'pain, fever, headache, blood thinner, heart attack prevention',
  'Acetylsalicylic Acid': 'pain, fever, headache, blood thinner',
  Metronidazole: 'stomach infection, diarrhea, amoebiasis, bacterial infection, giardiasis',
  Esomeprazole: 'acid reflux, heartburn, stomach pain, gastric ulcer, GERD, indigestion',
  Omeprazole: 'acid reflux, heartburn, stomach pain, gastric ulcer, GERD, indigestion',
  Pantoprazole: 'acid reflux, heartburn, stomach pain, gastric ulcer, GERD, indigestion',
  Ranitidine: 'acid reflux, heartburn, stomach pain, gastric ulcer, indigestion',
  Cetirizine: 'allergy, itching, allergic rhinitis, runny nose, sneezing, hives',
  Loratadine: 'allergy, itching, allergic rhinitis, runny nose, sneezing',
  Salbutamol: 'asthma, wheezing, shortness of breath, COPD, bronchospasm',
  Levosalbutamol: 'asthma, wheezing, shortness of breath, bronchospasm',
  Metformin: 'diabetes, high blood sugar, type 2 diabetes, insulin resistance',
  Glimepiride: 'diabetes, high blood sugar, type 2 diabetes',
  Atorvastatin: 'high cholesterol, heart disease prevention, dyslipidemia',
  Simvastatin: 'high cholesterol, heart disease prevention, dyslipidemia',
  Rosuvastatin: 'high cholesterol, heart disease prevention, dyslipidemia',
  Bisoprolol: 'high blood pressure, heart failure, hypertension, angina',
  Amlodipine: 'high blood pressure, hypertension, angina, chest pain',
  Losartan: 'high blood pressure, hypertension, kidney protection',
  Piroxicam: 'pain, inflammation, arthritis, joint pain',
  Diclofenac: 'pain, inflammation, arthritis, joint pain, back pain',
  Ketorolac: 'pain, inflammation, post operative pain, severe pain',
  Tramadol: 'moderate to severe pain, post operative pain',
  Dexamethasone: 'inflammation, allergy, asthma, immune disorders, swelling',
  Prednisolone: 'inflammation, allergy, asthma, immune disorders',
  Hydrocortisone: 'inflammation, allergy, skin rash, adrenal insufficiency',
  Mecobalamin: 'vitamin B12 deficiency, nerve health, neuropathy',
  Cyanocobalamin: 'vitamin B12 deficiency, nerve health, anemia',
  Cyclophosphamide: 'cancer, autoimmune disorders',
  Gefitinib: 'lung cancer, NSCLC',
  Anastrozole: 'breast cancer, hormone receptor positive breast cancer',
  Lignocaine: 'local anesthesia, pain relief, numbing',
  Lidocaine: 'local anesthesia, pain relief, numbing',
  Serratiopeptidase: 'swelling, inflammation, pain, tissue healing',
  Amoxicillin: 'bacterial infection, respiratory infection, ear infection, throat infection',
  Clavulanic: 'bacterial infection, antibiotic booster',
  Azithromycin: 'bacterial infection, respiratory infection, throat infection, sinusitis',
  Ciprofloxacin: 'bacterial infection, urinary tract infection, respiratory infection',
  Clarithromycin: 'bacterial infection, respiratory infection, throat infection, H pylori',
  Tinidazole: 'stomach infection, diarrhea, amoebiasis, bacterial infection',
  Ornidazole: 'stomach infection, diarrhea, amoebiasis, bacterial infection',
  Chlorpheniramine: 'allergy, itching, runny nose, cough, cold',
  Diphenhydramine: 'allergy, itching, runny nose, cough, cold, sleeplessness',
  Guaifenesin: 'cough, chest congestion, mucus',
  Dextromethorphan: 'dry cough',
  Ambroxol: 'cough, mucus, bronchitis',
  Bromhexine: 'cough, mucus, bronchitis',
  Phenylephrine: 'nasal congestion, stuffy nose, sinus pressure',
  Pseudoephedrine: 'nasal congestion, stuffy nose, sinus pressure',
  Domperidone: 'nausea, vomiting, stomach discomfort, gastroparesis',
  Metoclopramide: 'nausea, vomiting, stomach discomfort, migraine',
  Ondansetron: 'nausea, vomiting, chemotherapy sickness',
  Hyoscine: 'stomach cramps, abdominal pain, colic',
  Drotaverine: 'stomach cramps, abdominal pain, colic',
  Mefenamic: 'pain, menstrual cramps, fever',
  Tranexamic: 'heavy bleeding, blood loss',
  Folic: 'anemia, pregnancy, vitamin deficiency',
  Ferrous: 'anemia, iron deficiency, pregnancy',
  Calcium: 'calcium deficiency, bone health, osteoporosis',
  Cholecalciferol: 'vitamin D deficiency, bone health, osteoporosis',
  Levothyroxine: 'hypothyroidism, thyroid hormone deficiency',
  Carbimazole: 'hyperthyroidism, overactive thyroid',
  Insulin: 'diabetes, high blood sugar',
  Glipizide: 'diabetes, high blood sugar',
  Pioglitazone: 'diabetes, high blood sugar',
  Sitagliptin: 'diabetes, high blood sugar',
  Vildagliptin: 'diabetes, high blood sugar',
  Dapagliflozin: 'diabetes, high blood sugar, heart failure',
  Empagliflozin: 'diabetes, high blood sugar, heart failure',
  Captopril: 'high blood pressure, heart failure',
  Enalapril: 'high blood pressure, heart failure',
  Lisinopril: 'high blood pressure, heart failure',
  Perindopril: 'high blood pressure, heart failure',
  Ramipril: 'high blood pressure, heart failure',
  Valsartan: 'high blood pressure, heart failure',
  Telmisartan: 'high blood pressure, heart failure',
  Hydrochlorothiazide: 'high blood pressure, fluid retention',
  Furosemide: 'fluid retention, swelling, heart failure',
  Spironolactone: 'fluid retention, heart failure, high blood pressure',
  Digoxin: 'heart failure, irregular heartbeat',
  Warfarin: 'blood thinner, clot prevention',
  Rivaroxaban: 'blood thinner, clot prevention',
  Apixaban: 'blood thinner, clot prevention',
  Clopidogrel: 'blood thinner, heart attack prevention, stroke prevention',
  Carbamazepine: 'epilepsy, seizures, nerve pain',
  Phenytoin: 'epilepsy, seizures',
  'Sodium Valproate': 'epilepsy, seizures, bipolar disorder',
  Levetiracetam: 'epilepsy, seizures',
  Gabapentin: 'nerve pain, epilepsy, neuropathy',
  Pregabalin: 'nerve pain, epilepsy, neuropathy',
  Amitriptyline: 'depression, nerve pain, migraine prevention',
  Sertraline: 'depression, anxiety, OCD',
  Fluoxetine: 'depression, anxiety, OCD',
  Escitalopram: 'depression, anxiety',
  Alprazolam: 'anxiety, panic disorder',
  Diazepam: 'anxiety, muscle spasm, seizures',
  Lorazepam: 'anxiety',
  Clonazepam: 'epilepsy, seizures, panic disorder',
  Risperidone: 'schizophrenia, bipolar disorder',
  Olanzapine: 'schizophrenia, bipolar disorder',
  Haloperidol: 'schizophrenia, agitation',
  Levocetirizine: 'allergy, itching, hay fever, runny nose',
  Fexofenadine: 'allergy, itching, hay fever',
  Montelukast: 'asthma, allergic rhinitis, wheezing',
  Betahistine: 'vertigo, dizziness, Meniere disease',
  Cinnarizine: 'vertigo, dizziness, motion sickness',
  Dimenhydrinate: 'motion sickness, nausea, vomiting',
  Meclizine: 'motion sickness, vertigo',
  Loperamide: 'diarrhea',
  Racecadotril: 'diarrhea',
  'Oral Rehydration': 'diarrhea, dehydration',
  Sucralfate: 'stomach ulcer, gastric ulcer',
  Misoprostol: 'stomach ulcer, gastric ulcer',
  Bisacodyl: 'constipation',
  Lactulose: 'constipation',
  'Polyethylene Glycol': 'constipation',
  Senna: 'constipation',
  Docusate: 'constipation',
  Famotidine: 'acid reflux, heartburn, stomach pain',
  Magaldrate: 'acidity, heartburn, stomach pain, indigestion',
  Simethicone: 'gas, bloating, flatulence',
  Enzyme: 'indigestion, bloating, digestive aid',
  Pancreatin: 'indigestion, pancreatic insufficiency',
  Pepsin: 'indigestion, digestive aid',
  Charcoal: 'gas, bloating, poisoning',
  Benzydamine: 'sore throat, mouth pain, inflammation',
  'Povidone Iodine': 'antiseptic, wound cleaning, sore throat',
  Chlorhexidine: 'antiseptic, mouthwash, wound cleaning',
  Mupirocin: 'skin infection, bacterial infection',
  Fusidic: 'skin infection, bacterial infection',
  Clotrimazole: 'fungal infection, yeast infection',
  Miconazole: 'fungal infection, yeast infection',
  Ketoconazole: 'fungal infection, dandruff',
  Fluconazole: 'fungal infection, yeast infection',
  Terbinafine: 'fungal infection, ringworm',
  Permethrin: 'scabies, lice',
  'Benzyl Benzoate': 'scabies, lice',
  Calamine: 'itching, skin rash, sunburn',
  'Hydrocortisone Topical': 'skin rash, itching, eczema, inflammation',
  Betamethasone: 'skin rash, itching, eczema, inflammation',
  Clobetasol: 'skin rash, itching, eczema, severe inflammation',
  Tacrolimus: 'eczema, psoriasis',
  Pimecrolimus: 'eczema, psoriasis',
  'Coal Tar': 'psoriasis, dandruff',
  Salicylic: 'acne, dandruff, warts, psoriasis',
  'Benzoyl Peroxide': 'acne, pimples',
  Adapalene: 'acne, pimples',
  Tretinoin: 'acne, wrinkles, skin texture',
  Clindamycin: 'bacterial infection, acne',
  Erythromycin: 'bacterial infection, acne',
  Minocycline: 'bacterial infection, acne',
  Doxycycline: 'bacterial infection, acne, malaria',
  Azelaic: 'acne, rosacea',
  'Metronidazole Topical': 'rosacea, skin infection',
  'Permethrin Topical': 'scabies, lice',
  'Gamma Benzene': 'scabies, lice',
  Lindane: 'scabies, lice',
  Crotamiton: 'scabies, itching',
  Permethrin: 'scabies, lice',
  Malathion: 'lice',
  Phenothrin: 'lice',
  Dimethicone: 'lice',
  'Piperonyl Butoxide': 'lice',
  Pyrethrins: 'lice',
  Ivermectin: 'parasitic infection, scabies, strongyloidiasis',
  Albendazole: 'worm infection, parasites',
  Mebendazole: 'worm infection, parasites',
  Praziquantel: 'worm infection, schistosomiasis',
  Artemether: 'malaria',
  Lumefantrine: 'malaria',
  Artesunate: 'malaria',
  Quinine: 'malaria',
  Chloroquine: 'malaria',
  Primaquine: 'malaria',
  Proguanil: 'malaria prophylaxis',
  Atovaquone: 'malaria',
  Mefloquine: 'malaria',
  Doxycycline: 'malaria prophylaxis, bacterial infection',
  Sulfadoxine: 'malaria',
  Pyrimethamine: 'malaria, toxoplasmosis',
  'Co Trimoxazole': 'bacterial infection, urinary tract infection, pneumonia',
  Sulfamethoxazole: 'bacterial infection, urinary tract infection',
  Trimethoprim: 'bacterial infection, urinary tract infection',
  Nitrofurantoin: 'urinary tract infection',
  Fosfomycin: 'urinary tract infection',
  Cefixime: 'bacterial infection, urinary tract infection, throat infection',
  Cefuroxime: 'bacterial infection, urinary tract infection, respiratory infection',
  Cefpodoxime: 'bacterial infection, respiratory infection',
  Ceftriaxone: 'bacterial infection, severe infection, meningitis',
  Cefotaxime: 'bacterial infection, severe infection',
  Piperacillin: 'bacterial infection, severe infection',
  Tazobactam: 'bacterial infection, severe infection, antibiotic booster',
  Meropenem: 'bacterial infection, severe infection',
  Imipenem: 'bacterial infection, severe infection',
  Doripenem: 'bacterial infection, severe infection',
  Ertapenem: 'bacterial infection, severe infection',
  Colistin: 'bacterial infection, severe infection',
  Polymyxin: 'bacterial infection, severe infection',
  Vancomycin: 'bacterial infection, severe infection',
  Teicoplanin: 'bacterial infection, severe infection',
  Linezolid: 'bacterial infection, severe infection',
  Daptomycin: 'bacterial infection, severe infection',
  Tigecycline: 'bacterial infection, severe infection',
  Fidaxomicin: 'C diff infection, diarrhea',
  Rifaximin: 'hepatic encephalopathy, travelers diarrhea',
  Acyclovir: 'herpes, chickenpox, shingles, viral infection',
  Valacyclovir: 'herpes, shingles, cold sores',
  Famciclovir: 'herpes, shingles',
  Oseltamivir: 'influenza, flu',
  Zanamivir: 'influenza, flu',
  Ribavirin: 'viral infection, hepatitis C',
  Sofosbuvir: 'hepatitis C',
  Daclatasvir: 'hepatitis C',
  Velpatasvir: 'hepatitis C',
  Ledipasvir: 'hepatitis C',
  Glecaprevir: 'hepatitis C',
  Pibrentasvir: 'hepatitis C',
  Tenofovir: 'hepatitis B, hepatitis C, HIV',
  Entecavir: 'hepatitis B',
  Lamivudine: 'hepatitis B, HIV',
  Adefovir: 'hepatitis B',
  Telbivudine: 'hepatitis B',
  Interferon: 'hepatitis, viral infection',
  Ribavirin: 'hepatitis C',
  Boceprevir: 'hepatitis C',
  Simeprevir: 'hepatitis C',
  Paritaprevir: 'hepatitis C',
  Ritonavir: 'HIV, antiviral booster',
  Lopinavir: 'HIV',
  Darunavir: 'HIV',
  Atazanavir: 'HIV',
  Efavirenz: 'HIV',
  Nevirapine: 'HIV',
  Etravirine: 'HIV',
  Rilpivirine: 'HIV',
  Dolutegravir: 'HIV',
  Elvitegravir: 'HIV',
  Raltegravir: 'HIV',
  Bictegravir: 'HIV',
  Cabotegravir: 'HIV',
  Maraviroc: 'HIV',
  Enfuvirtide: 'HIV',
  Zidovudine: 'HIV',
  Stavudine: 'HIV',
  Didanosine: 'HIV',
  Abacavir: 'HIV',
  Emtricitabine: 'HIV, hepatitis B',
  'Tenofovir Alafenamide': 'HIV, hepatitis B',
  'Tenofovir Disoproxil': 'HIV, hepatitis B',
  Flucytosine: 'fungal infection',
  Amphotericin: 'fungal infection, severe fungal infection',
  Caspofungin: 'fungal infection',
  Micafungin: 'fungal infection',
  Anidulafungin: 'fungal infection',
  Voriconazole: 'fungal infection',
  Posaconazole: 'fungal infection',
  Isavuconazole: 'fungal infection',
  Itraconazole: 'fungal infection',
  Echinocandin: 'fungal infection',
  Griseofulvin: 'fungal infection',
  Nystatin: 'fungal infection, oral thrush',
  'Amphotericin B': 'fungal infection, severe fungal infection',
  Pentamidine: 'pneumonia, parasitic infection',
  Atovaquone: 'pneumonia, malaria',
  Sulfadiazine: 'toxoplasmosis, bacterial infection',
  Pyrimethamine: 'toxoplasmosis, malaria',
  Leucovorin: 'folinic acid rescue, anemia',
  Methotrexate: 'cancer, rheumatoid arthritis, psoriasis',
  Azathioprine: 'autoimmune disorders, transplant rejection',
  Mycophenolate: 'transplant rejection, autoimmune disorders',
  'Tacrolimus Systemic': 'transplant rejection, autoimmune disorders',
  Cyclosporine: 'transplant rejection, autoimmune disorders',
  Sirolimus: 'transplant rejection',
  Everolimus: 'transplant rejection, cancer',
  Leflunomide: 'rheumatoid arthritis',
  Sulfasalazine: 'rheumatoid arthritis, ulcerative colitis',
  Mesalazine: 'ulcerative colitis, Crohn disease',
  Budesonide: 'inflammatory bowel disease, asthma',
  Prednisone: 'inflammation, allergy, autoimmune disorders',
  'Betamethasone Systemic': 'inflammation, allergy, fetal lung maturity',
  'Dexamethasone Systemic': 'inflammation, allergy, COVID, brain swelling',
  Methylprednisolone: 'inflammation, allergy, autoimmune disorders',
  'Hydrocortisone Systemic': 'adrenal insufficiency, inflammation, allergy',
  Deflazacort: 'inflammation, allergy, muscular dystrophy',
  Triamcinolone: 'inflammation, allergy, skin rash',
  Fluocinolone: 'skin rash, inflammation',
  Mometasone: 'skin rash, inflammation, allergy',
  Fluticasone: 'asthma, allergy, nasal congestion',
  Beclomethasone: 'asthma, allergy',
  'Budesonide Inhaler': 'asthma, COPD',
  Formoterol: 'asthma, COPD',
  Salmeterol: 'asthma, COPD',
  Indacaterol: 'COPD, asthma',
  Olodaterol: 'COPD',
  Tiotropium: 'COPD, asthma',
  Ipratropium: 'COPD, asthma',
  Aclidinium: 'COPD',
  Glycopyrrolate: 'COPD, asthma',
  Umeclidinium: 'COPD',
  Vilanterol: 'COPD, asthma',
  Acetylcysteine: 'mucus, cough, paracetamol overdose',
  Bromhexine: 'cough, mucus',
  Carbocisteine: 'cough, mucus',
  Erdosteine: 'cough, mucus',
  Ambroxol: 'cough, mucus',
  Guaifenesin: 'cough, congestion',
  Dextromethorphan: 'dry cough',
  Pholcodine: 'dry cough',
  Butamirate: 'dry cough',
  Codeine: 'pain, dry cough',
  Morphine: 'severe pain, cancer pain',
  Fentanyl: 'severe pain, cancer pain',
  Oxycodone: 'severe pain, cancer pain',
  Buprenorphine: 'severe pain, opioid dependence',
  Tapentadol: 'moderate to severe pain',
  Nalbuphine: 'pain',
  Pentazocine: 'pain',
  Pethidine: 'pain',
  Meperidine: 'pain',
  Nefopam: 'pain',
  Flupirtine: 'pain',
};

function normalizeIngredient(name) {
  return String(name || '')
    .toLowerCase()
    .replace(/[^a-z0-9+]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function usesForIngredient(rawName) {
  const norm = normalizeIngredient(rawName);
  if (!norm) return [];

  // Exact match first.
  const direct = Object.keys(INGREDIENT_USES).find(
    (k) => normalizeIngredient(k) === norm
  );
  if (direct) return INGREDIENT_USES[direct].split(',').map((s) => s.trim());

  // Substring match: e.g. "Esomeprazole Magnesium" contains "Esomeprazole".
  const substring = Object.keys(INGREDIENT_USES).find(
    (k) => norm.includes(normalizeIngredient(k))
  );
  if (substring) return INGREDIENT_USES[substring].split(',').map((s) => s.trim());

  // Compound ingredients separated by + / and.
  const parts = norm.split(/\+|\band\b|\//).map((s) => s.trim()).filter(Boolean);
  const collected = [];
  for (const part of parts) {
    const key = Object.keys(INGREDIENT_USES).find(
      (k) => normalizeIngredient(k) === part || part.includes(normalizeIngredient(k))
    );
    if (key) collected.push(...INGREDIENT_USES[key].split(',').map((s) => s.trim()));
  }
  return collected;
}

function usesForProduct(product) {
  const ingredientNames = (product.ingredients || []).map((i) => i.name);
  const all = new Set();
  for (const name of ingredientNames) {
    for (const use of usesForIngredient(name)) all.add(use);
  }
  return Array.from(all);
}

module.exports = { usesForProduct };
